# Generated by Django 5.0.6 on 2024-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0002_remove_dailytimelog_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
