# Generated by Django 5.0.6 on 2024-08-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0004_customuser'),
        ('employee_management', '0005_auto_20240805_1454'),
    ]

    operations = [
    ]
