# Generated by Django 5.0.6 on 2024-08-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_management', '0008_alter_reimbursement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
